### ISSUE TITLE
'Redeem Coin' Error

### ISSUE THREAD

**Issue by lima2tiga** [pearlxcore/ShopeeAutobuyBot#16]
Hi Admin,

After several attempts the coin claim function was unsuccessful in any mode. This function has no problem during version 2.3.2.0

![image](https://user-images.githubusercontent.com/131317112/234599797-4ce6e988-2e56-4664-ac09-37a1b6febe07.png)

**Comment by pearlxcore** [comment]
element editor -> checkout page

redeem coin checkbox xpath : `//*[@id="main"]/div/div[2]/div/div[2]/div[3]/div[2]/div[2]/label/div`

![image](https://user-images.githubusercontent.com/36906814/235303092-ec8d602a-d9e3-4a51-af9c-ea3e2abec7da.png)

**Comment by lima2tiga** [comment]
Thx admin. Bug fix...
