### ISSUE TITLE
Error : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lima2tiga** [pearlxcore/ShopeeAutobuyBot#18]
Hello Hi Admin..

How to fix error **Object reference not set to an instance of an object.** appear when place order button activated?

Log as below

![image](https://github.com/pearlxcore/Shopee-Autobuy-Bot/assets/131317112/3f4af5ac-01ff-4560-b0e3-675f9fa7d337)

Thanks Admin..

**Comment by xxbyrsalphaxx** [comment]
Hi, i've also encountered this problem, any fixes yet?

**Comment by pearlxcore** [comment]
Check element at Place Order button. If Shopee update the element class name, update new XPath at Element editor
