### ISSUE TITLE
Error for bot version 2.4.5 (Missing some product details)

### ISSUE THREAD

**Issue by xxbyrsalphaxx** [pearlxcore/ShopeeAutobuyBot#20]
Error as shown as below. Updated elements.

Should i put the source code file inside the v2.4.5.0 file?
![Screenshot 2023-10-07 152954](https://github.com/pearlxcore/Shopee-Autobuy-Bot/assets/145514575/da9eb9c1-9fcf-47c5-8f39-ecf180c3953e)

**Comment by pearlxcore** [comment]
No need source code to fix that. Just a bug which I will fix it in later version. Was tweaking the code and overlooked the problem. Temporary solution is by saving a profile with the product detail and other preferred settings and load it back and start the job.

**Comment by pearlxcore** [comment]
This error related to the sound player. For temporary solution, untick play sound checkbox.

https://github.com/pearlxcore/Shopee-Autobuy-Bot/issues/21#issuecomment-1753519217
