### ISSUE TITLE
An Error Occured On Line 482: Object not set to an instance of an object

### ISSUE THREAD

**Issue by BardQalish** [pearlxcore/ShopeeAutobuyBot#21]
Hi just got error log that show line 482 issue.
![image](https://github.com/pearlxcore/Shopee-Autobuy-Bot/assets/147392576/df690e3c-c931-41b6-82fb-db34596e1774)

how to solve this.

**Comment by pearlxcore** [comment]
> Hi just got error log that show line 482 issue. ![image](https://user-images.githubusercontent.com/147392576/273557449-df690e3c-c931-41b6-82fb-db34596e1774.png)
> 
> how to solve this.

This is an error related to sound player right before placing order. I removed all stuff related to sound player and will replace with notifyicon. Latest commit already fix the error. But will release the compiled version later. For temporary fix, untick play sound checkbox.
