### ISSUE TITLE
Error@ Place Order, need manually press the place order

### ISSUE THREAD

**Issue by Mikazuki02** [pearlxcore/ShopeeAutobuyBot#23]
Hiii 

I received an error when trying to place my order. Can't continue in place order screen. Error log as below. 
Thanks you so much in advance @pearlxcore 

[17:56:46] Current element : OrderPrice (//div[contains(@class, '_9F3E9v')])
An error occurred on line line 626: Timed out after 5 seconds
![123123](https://github.com/pearlxcore/Shopee-Autobuy-Bot/assets/148540471/6fc1032c-1b43-4f51-970d-558142a3089f)

**Comment by pearlxcore** [comment]
Hi. the issue is program cannot detect the OrderPrice element (shopee often update it) in checkout page and i was so dumb to put the unimportant checks in checkout page. Will fix in later version.

**Comment by pearlxcore** [comment]
https://github.com/pearlxcore/Shopee-Autobuy-Bot/releases/tag/2.5.3.0

**Comment by Mikazuki02** [comment]
Thank you so much for everything. It works nowww.
