### ISSUE TITLE
error on line 601

### ISSUE THREAD

**Issue by mshaf6666** [pearlxcore/ShopeeAutobuyBot#27]
![IMG_6922](https://github.com/pearlxcore/Shopee-Autobuy-Bot/assets/149071916/6b9653e6-78fc-4ce3-a5f4-ae9dccbb46ea)

this always happen when the bot wants to press buy now. may i know why?

**Comment by pearlxcore** [comment]
You need to update the website element in element editor.

https://github.com/pearlxcore/Shopee-Autobuy-Bot/wiki/Shopee-website-element
