### ISSUE TITLE
Auto Refresh issue

### ISSUE THREAD

**Issue by mshaf6666** [pearlxcore/ShopeeAutobuyBot#28]
Auto refresh page set to 0 second is not working. Browser did not auto refresh

**Comment by Banana-97** [comment]
Auto refresh page set to 0 = No refresh, I believe this is the intention

**Comment by mshaf6666** [comment]
you sure? previous patch im using set to 0 means will always refresh

**Comment by pearlxcore** [comment]
Fixed in [v2.5.6.0](https://github.com/pearlxcore/Shopee-Autobuy-Bot/releases/tag/2.5.6.0)
