### ISSUE TITLE
Error@ stuck at place order page

### ISSUE THREAD

**Issue by lima2tiga** [pearlxcore/ShopeeAutobuyBot#9]
Hello Hi..

I received an error when trying to place my order. Can't continue in place order screen. Error log as below. Thx @pearlxcore..

[10:05:35] Cart page loaded.
[10:05:35] Click 'Check Out'.
[10:05:35] Checkout page loaded.
[10:05:42] [S5] Waiting for element : //div[contains(@class, '_4MGXB1')]
[10:05:42] no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class, '_4MGXB1')]"}
  (Session info: chrome=112.0.5615.138)
[10:05:43] Job aborted.

![image](https://user-images.githubusercontent.com/131317112/233239219-29c5ab4e-c8f1-42da-9fa0-d8a87b5cc77d.png)

**Comment by lima2tiga** [comment]
The element displayed in log '_4MGXB1' could not be identified. Have tried to modify the existing element in the place order section still failed.

**Comment by pearlxcore** [comment]
Hi, the xpath is hardcoded in the program. I thought it would never be changed. Looks like I will need to store the xpath value locally like in text file so that users can change the xpath manually whenever Shopee updates it.

It is the xpath for order price in checkout page. Current value is '_9F3E9v'. I will add changes to store xpath value later.

**Comment by lima2tiga** [comment]
Hi, Thanks for the feedback. Agree with the admin's suggestion to give access lets the user to edit manually itself if the element section have any update from sh@pee. I look forward to the latest updates to give further feedback on the bot's progress. 

Happy Eid al-Fitr

![image](https://user-images.githubusercontent.com/131317112/233757506-22af1755-7684-40e0-ad3d-80e45ecdd950.png)

**Comment by pearlxcore** [comment]
Hope version [2.3.3.0](https://github.com/pearlxcore/ShopeeAutobuyBot/releases/tag/2.3.3.0) fixed this problem

**Comment by lima2tiga** [comment]
Thanks admin for the latest update.
